class IfNode

  def real_gen
    $pygen.if condition, when_true, when_false
  end
end


# Generated by case-when translation
class PythonElIf < IfNode

  def real_gen
    $pygen.elif condition, when_true, when_false
  end
end